on: [push, pull_request]
name: Test
jobs:
    test:
        strategy:
          matrix:
            go-version: [1.13, 1.14]
            platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:
        - name: Install Go
          uses: actions/setup-go@v1
          with:
            go-version: ${{ matrix.go-version }}

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Test
          run: go test -race ./...

        - name: Install linter
          run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8"
        
        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: go mod download
        
        - name: Build
          env:
            GOPROXY: "https://proxy.golang.org"
          run: go build -race .
    
        - name: Lint
          run: |
            export PATH=$PATH:~/go/bin
            golangci-lint run --deadline=10m \
            --disable-all --enable govet \
            --enable staticcheck --enable gosimple \
            --enable unconvert --enable ineffassign \
            --enable structcheck --enable goimports \
            --enable misspell --enable unparam --enable golint